### ISSUE TITLE
HELP !

### ISSUE THREAD

**Issue by iamjosave14202** [VoxelCubes/PanelCleaner#31] opened 2024-01-04 07:08 UTC
![image](https://github.com/VoxelCubes/PanelCleaner/assets/55599699/83b64a8d-35c4-4200-b8a0-31afae6b7531)

**Comment by iamjosave14202** [comment] 2024-01-05 09:13
Output worker encountered an error:
    <class 'UnicodeDecodeError'>: Traceback (most recent call last):
      File "pcleaner\gui\worker_thread.py", line 141, in run
      File "pcleaner\gui\mainwindow_driver.py", line 1064, in generate_output
      File "pcleaner\gui\processing.py", line 228, in generate_output
      File "pcleaner\preprocessor.py", line 74, in prep_json_file
      File "pathlib.py", line 1059, in read_text
      File "encodings\cp874.py", line 23, in decode
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 350: character maps to <undefined>
    
    'charmap' codec can't decode byte 0x88 in position 350: character maps to <undefined>

**Comment by VoxelCubes** [comment] 2024-01-05 23:57
Hmm, This appears to be a duplicate of #27 involving windows' weird character encoding messing up the unicode. I need to check where in the pipeline I let Python assume something was unicode without accounting for the possibility of windows doing something strange. 
For the other issue, he thankfully provided me with example material to test where this goes wrong. I just need to find the time to investigate properly.

As for you, I suggest you can rename your image files and/or place them into a different folder such that the full path to the image doesn't contain any non-ascii characters. That'll make it work again until I fix this properly.

**Closed by VoxelCubes** 2024-01-05 23:57 UTC

**Comment by iamjosave14202** [comment] 2024-01-06 08:06
ummm and Can the text in this image be removed? How do you set it up?
![image](https://github.com/VoxelCubes/PanelCleaner/assets/55599699/3e859600-8df5-4db3-a621-5994442285a1)

**Comment by VoxelCubes** [comment] 2024-01-06 12:06
What exactly is the question here? Since it appears to have worked. Any
remaining text either wasn't detected, or couldn't be cleaned properly,
needing manual work.
You can also try tweaking the profile options to make cleaning more/less
aggressive.

If you want to save the file as you see it right there, either click on the
three dots in the top right and select the save option to export that exact
step in the pipeline, or go to the right panel, the box for process, and
make sure it's set to cleaning, then press start. Also, make sure the save
output checkbox in the output section is enabled, otherwise it won't save
any files. If you run the cleaner without it, you can just enable it and
run the cleaner again to export.

Hope that helps.
