### ISSUE TITLE
When I use the cli version with cmd, if the split long strip option is True, the results are not saved in the cleaned folder!

### ISSUE THREAD

**Issue by esmail-mkh** [VoxelCubes/PanelCleaner#131] opened 2024-12-05 08:37 UTC
**Describe the bug**
When I use the cli version with cmd, if the split long strip option is True, the results are not saved in the cleaned folder, And they don't even merge

**Expected behavior**
to save successfully

**Comment by VoxelCubes** [comment] 2024-12-05 12:32
Strange, it works for me. Try using the default profile by adding `-p default`, so simply run `pcleaner clean -p default "image file or folder path"`

~Could you also attach a debug log, please? You can get it easily from the gui by pressing the "Open Log" button in the bottom right of the main window, just select the previous session, the log file will have remembered it.~
I just realized that the cli doesn't log to the log file, how did I forget that? Well, I'll be adding that to the next version.
For now, just run `pcleaner clean -p default "image file or folder path" --debug`, copy the terminal output and remove your username from the output. 

Also, just a short public service announcement: cmd is terrible, upgrade to the Windows terminal https://apps.microsoft.com/detail/9n0dx20hk701 That's microsoft's new terminal that supports color, symbols, tabs, and looks a lot less ugly. It's even open source, surprisingly enough!

**Comment by esmail-mkh** [comment] 2024-12-05 15:23
> Strange, it works for me. Try using the default profile by adding `-p default`, so simply run `pcleaner clean -p default "image file or folder path"`
> 
> ~Could you also attach a debug log, please? You can get it easily from the gui by pressing the "Open Log" button in the bottom right of the main window, just select the previous session, the log file will have remembered it.~ I just realized that the cli doesn't log to the log file, how did I forget that? Well, I'll be adding that to the next version. For now, just run `pcleaner clean -p default "image file or folder path" --debug`, copy the terminal output and remove your username from the output.
> 
> Also, just a short public service announcement: cmd is terrible, upgrade to the Windows terminal https://apps.microsoft.com/detail/9n0dx20hk701 That's microsoft's new terminal that supports color, symbols, tabs, and looks a lot less ugly. It's even open source, surprisingly enough!

Ok I will try, and I just realized that when I use my own profile, the results save in cache folder😅, i don't know why.

**Comment by VoxelCubes** [comment] 2024-12-05 17:09
Aha, I tracked down the issue. You have merge after split disabled in the profile, which will prevent merging the images after they were split. That's your issue here, fix your profile.

But you did come across a bug! The cli doesn't properly fix the save location of split files if they aren't getting merged. The gui does, so my testing was insufficient. So they should've been saved in the original directory of the image they were split from, not the temporary folder the splits were put in inside cache.

Case closed, I'll make a new hotfix to patch the save location of non-merged split files in cli mode, and you go enable merge after split in your profile.

**Closed by VoxelCubes** 2024-12-05 17:09 UTC
Labels: bug

**Comment by VoxelCubes** [comment] 2024-12-05 18:28
Version 2.11.2 now live on pypi, release update coming soon.

**Comment by esmail-mkh** [comment] 2024-12-05 18:45
> Version 2.11.2 now live on pypi, release update coming soon.

Thank you

**Comment by esmail-mkh** [comment] 2024-12-06 06:18
> Version 2.11.2 now live on pypi, release update coming soon.

hi, i tested it today with debug mode in 2.11.2 hotfix but it seems that problem still doesn't fixed!

this is error:
```
2024-12-06 09:45:04.773 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\001.webp.Skipping.
2024-12-06 09:45:04.774 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\002.webp.Skipping.
2024-12-06 09:45:04.775 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\003.webp.Skipping.
2024-12-06 09:45:04.776 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\004.webp.Skipping.
2024-12-06 09:45:04.776 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\005.webp.Skipping.
2024-12-06 09:45:04.777 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\006.webp.Skipping.
2024-12-06 09:45:04.778 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\007.webp.Skipping.
2024-12-06 09:45:04.779 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\008.webp.Skipping.
2024-12-06 09:45:04.780 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\009.webp.Skipping.
2024-12-06 09:45:04.780 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\010.webp.Skipping.
2024-12-06 09:45:04.781 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\011.webp.Skipping.
2024-12-06 09:45:04.782 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\012.webp.Skipping.
2024-12-06 09:45:04.783 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\013.webp.Skipping.
2024-12-06 09:45:04.783 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\014.webp.Skipping.
2024-12-06 09:45:04.784 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\015.webp.Skipping.
2024-12-06 09:45:04.785 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\016.webp.Skipping.
2024-12-06 09:45:04.786 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\017.webp.Skipping.
2024-12-06 09:45:04.787 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\018.webp.Skipping.
2024-12-06 09:45:04.787 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\019.webp.Skipping.
2024-12-06 09:45:04.788 | ERROR    | pcleaner.main:merge_export_splits:993 - Could not find all split images for M:\Manhwa\Esmaeil\x\Files\Eng\Chapter 49\020.webp.Skipping.
```

**Comment by VoxelCubes** [comment] 2024-12-06 12:06
I can't reproduce the issue. Are you sure you updated? Because a `pip install pcleaner` won't upgrade your install, unless you specify `pip install pcleaner --upgrade`. You can check with `pcleaner -v`.

If you are on 2.11.2, then please attach a full debug log, you can now get it from your logfile, the gui, or by copying the entire terminal output. This snippet you showed is too short to be helpful, unfortunately.

**Comment by esmail-mkh** [comment] 2024-12-06 12:39
> I can't reproduce the issue. Are you sure you updated? Because a `pip install pcleaner` won't upgrade your install, unless you specify `pip install pcleaner --upgrade`. You can check with `pcleaner -v`.
> 
> If you are on 2.11.2, then please attach a full debug log, you can now get it from your logfile, the gui, or by copying the entire terminal output. This snippet you showed is too short to be helpful, unfortunately.

I finally came to a conclusion, I realized that it could not save because I had transferred the pcleaner folder that was inside AppData to another drive using Symbolic Link because of my C drive was almost full, but now  I changed the cache and models folder address from the config file and it working so well!

**Comment by VoxelCubes** [comment] 2024-12-06 12:45
Awesome, glad you solved the issue! Also good to hear that changing the cache dir manually worked out, that isn't something I tested recently. Thanks!

Happy cleaning
